AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaFunctionOverHttps:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      FunctionName: samPoc
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/users'
            Method: GET