name: Lambda Pipeline

on: 
  push:
    branches:
      - master

jobs:
  deployLambda:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '18.x'
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::968225077300:role/github-role
      - name: Npm Install
        run: npm ci

      - name: Build and Deploy
        run: |
          sam build --template template.yaml
          sam deploy 
            --resolve-s3 \
            --no-confirm-changeset \ 
            --no-fail-on-empty-changeset \
            --stack-name sam-poc \
            --capabilities CAPABILITY_IAM
